config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="empresa:business-list"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('i18n/', include('django.conf.urls.i18n')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("lab_ati.users.urls", namespace="users")), 
    path("proveedor/", include("lab_ati.proveedor.urls")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("business/", include("lab_ati.cliente.urls")),
    # Business urls
    path("business/", include("lab_ati.empresa.urls", namespace="business")),
    # Employee urls
    path("business/", include("lab_ati.areadenegocio.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    #path('proveedor/crear', createProveedor, name='createProveedor')
    
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lab_ati/cliente/urls.py
from django.urls import path
from lab_ati.cliente.views import (
    clientes,
    ver_cliente,
    crear_cliente,
    eliminar_cliente, 
    editar_cliente
    )

urlpatterns = [
    path('<slug:business_id>/clients/', clientes, name='clients'),
    path('<slug:business_id>/clients/create', crear_cliente, name='create-client'),
    path('<slug:business_id>/clients/<slug:id>', ver_cliente, name='detail-client'),
    path('<slug:business_id>/clients/delete/<slug:id>', eliminar_cliente, name='delete-client'),
    path('<slug:business_id>/clients/edit/<slug:id>', editar_cliente, name='edit-client')
]

lab_ati/empresa/urls.py
from django.urls import path
from . import views

app_name = "empresa"

urlpatterns = [
    path("", views.BusinessListView.as_view(), name="business-list"),
    path("create", views.CreateBusinessView.as_view(), name="create-business"),
    path("details/<slug:pk>", views.BusinessDetailsView.as_view(), name="business-details"),
    path("edit/<slug:pk>", views.EditBusinessView.as_view(), name="edit-business"),
    path("delete/<slug:pk>", views.DeleteBusinessView.as_view(), name="delete-business"),
    path("<slug:business_id>/employees/create", views.CreateEmployeeView.as_view(), name="create-employee"),
    path("<slug:business_id>/employees/edit/<slug:pk>", views.EditEmployeeView.as_view(), name="edit-employee"),
    path("<slug:business_id>/employees/", views.ListEmployeeView.as_view(), name="list-employee"),
    path("<slug:business_id>/employees/delete/<slug:pk>", views.DeleteEmployeeView.as_view(), name="delete-employee"),
    path("<slug:business_id>/employees/<slug:pk>", views.DetailEmployeeView.as_view(), name="detail-employee"),
    path("guardar-logo/<slug:business_id>", views.actualizar_logo_empresa, name="update-logo-employee"),
]

lab_ati/users/urls.py
from django.urls import path

from lab_ati.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lab_ati/areadenegocio/models.py
from django.db import models
from lab_ati.empresa.models import Empresa
from django.contrib.postgres.fields import ArrayField

class AreaDeNegocio(models.Model):
    id_empresa = models.ForeignKey(
        Empresa,
        on_delete=models.CASCADE,
        verbose_name="Empresa relacionada",
        related_name="empresa_del_area_de_negocio",
        null=True, blank=True
    )
    nombre_empresa = models.CharField("Nombre de la empresa", max_length=255)
    nombre = models.CharField("Nombre del área de negocio", max_length=255)
    pais = ArrayField(
        models.CharField("País", max_length=255),
        blank=True,
        null=True,
    )
    descripcion = models.TextField("Descripción del área de negocio", null=True, blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Áreas de Negocio"

lab_ati/areadenegocio/forms.py
from django import forms
from lab_ati.areadenegocio.models import AreaDeNegocio
from lab_ati.empresa.models import Empresa
from django_countries import countries

class AreaDeNegocioForm(forms.ModelForm):

    id_empresa = forms.ModelChoiceField(
        queryset=Empresa.objects.all(),
        label="Empresa relacionada",
        to_field_name="id",
        widget=forms.Select(attrs={"class": "form-select"}),
    )

    pais = forms.MultipleChoiceField(
        choices=[],
        label="Países",
        widget=forms.SelectMultiple(attrs={"class": "form-select"}),
        required=False,
    )

    def get_countries_choices(self):
        return [(code, name) for code, name in countries]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["id_empresa"].label_from_instance = self.label_from_instance
        self.fields["pais"].choices = self.get_countries_choices()

    def label_from_instance(self, obj):
        return f"{obj.id} - {obj.nombre}"

    class Meta:
        model = AreaDeNegocio
        fields = ['nombre', 'pais', 'descripcion', 'id_empresa']

        

lab_ati/cliente/forms.py
from django import forms
from lab_ati.cliente.models import Cliente

class ClienteForm(forms.ModelForm):

    # Validación de teléfonos
    def clean(self):
        cleaned_data = super().clean()
        tlf_celular = cleaned_data.get('tlf_celular')
        whatsapp = cleaned_data.get('whatsapp')
        
        # Verificar que al menos un campo no está vacío
        if not tlf_celular and not whatsapp:
           msg = ('Debe ingresar al menos un número de teléfono')
           self.add_error('tlf_celular', msg)
           self.add_error('whatsapp', msg)
        
        return cleaned_data

    class Meta:
        model = Cliente
        fields = '__all__'

lab_ati/proveedor/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
  class Meta:
    model = Proveedor
    fields = '__all__'
 

lab_ati/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

lab_ati/areadenegocio/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from lab_ati.areadenegocio.forms import AreaDeNegocioForm
from lab_ati.areadenegocio.models import AreaDeNegocio

def areasdenegocio(request, business_id):
    context = {}
    context['business_id'] = business_id
    areasdenegocio = AreaDeNegocio.objects.all()  # Consulta todas las áreas de negocio
    order = request.GET.get('order')

    # Aplicar el ordenamiento según el parámetro recibido
    if order == 'empresa':
        areasdenegocio = areasdenegocio.order_by('id_empresa')
    elif order == 'area_negocio':
        areasdenegocio = areasdenegocio.order_by('nombre')
    elif order == 'pais':
        areasdenegocio = areasdenegocio.order_by('pais')

    filtrar_por_empresa = request.GET.get('filtrar_por_empresa')

    if filtrar_por_empresa == 'si':
        areasdenegocio = areasdenegocio.filter(id_empresa=business_id)

    context['areasdenegocio'] = areasdenegocio

    return render(request, 'pages/areanegocio/index.html', context)

def ver_areadenegocio(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    areadenegocio = AreaDeNegocio.objects.get(id = id)
    context['form'] = AreaDeNegocioForm(request.POST or None, instance=areadenegocio)
    context["list_link"] = reverse("areasdenegocio", kwargs={"business_id": business_id} )
    context["nombre_empresa"] = areadenegocio.id_empresa

    return render(request, 'pages/areanegocio/verAreaNegocio.html', context)


def crear_areadenegocio(request, business_id):
    context = {}
    context['business_id'] = business_id
    
    if request.method == 'POST':
        form = AreaDeNegocioForm(request.POST)
        
        if form.errors:
            print(form.errors)

        if form.is_valid():
            area_de_negocio = form.save()  # Guardar el área de negocio en la base de datos

            return redirect('areasdenegocio', business_id = business_id)
    else:
        form = AreaDeNegocioForm()

    context['form'] = form
    context["list_link"] = reverse("areasdenegocio", kwargs={"business_id": business_id} )

    return render(request, 'pages/areanegocio/create.html', context)

def eliminar_areadenegocio(request, id, business_id):
    areadenegocio = AreaDeNegocio.objects.get(id = id)
    areadenegocio.delete()
    context = {}
    context["list_link"] = reverse("areasdenegocio", kwargs={"business_id": business_id} )
    context['business_id'] = business_id

    return redirect('areasdenegocio', business_id = business_id)

def editar_areadenegocio(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    areadenegocio = AreaDeNegocio.objects.get(id = id)
    form = AreaDeNegocioForm(request.POST or None, instance=areadenegocio)
    if form.is_valid() and request.POST:
        savedForm = form.save()
        return redirect('areasdenegocio', business_id = business_id)
    
    context['form'] = form
    context["list_link"] = reverse("areasdenegocio", kwargs={"business_id": business_id} )

    return render(request, 'pages/areanegocio/editar.html', context)

lab_ati/cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lab_ati.cliente.models import Cliente
from lab_ati.cliente.forms import ClienteForm
from lab_ati.empresa.forms import SocialMediaFormset
from lab_ati.empresa.models import SocialMedia
from lab_ati.utils.social_media import add_social_media
from django.urls import reverse

def clientes(request, business_id):
    context = {}
    context['business_id'] = business_id
    clientes = Cliente.objects.filter(empresa__id__contains = business_id)
    context['clientes'] = clientes
    return render(request, 'pages/clientes/index.html', context)

def ver_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    context['form'] = ClienteForm(request.POST or None, instance=cliente)
    context['social_medias'] = cliente.redes_sociales.all()
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    return render(request, 'pages/clientes/verCliente.html', context)

def crear_cliente(request, business_id):
    context = {}
    context['business_id'] = business_id
    form = ClienteForm(request.POST or None)
    if form.is_valid():
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST)
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)
        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=SocialMedia.objects.none())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return render(request, 'pages/clientes/crear.html', context)


def eliminar_cliente(request, id, business_id):
    cliente = Cliente.objects.get(id = id)
    cliente.delete()
    context = {}
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return redirect('clients', business_id = business_id)

def editar_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid() and request.POST:
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST, queryset=savedForm.redes_sociales.all())
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)

        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=cliente.redes_sociales.all())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context["editing_social"] = True

    return render(request, 'pages/clientes/editar.html', context)

lab_ati/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

lab_ati/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

lab_ati/templates/pages/employees/delete.html
{% extends "../../base.html" %}
{% load i18n %}

{% block content %}
<section class="general-container w-100 h-100">
    {% include "../../common/navigation-bar.html" with back_link=request.META.HTTP_REFERER enlace=list_link %}
    <section class="w-100 d-flex flex-column justify-content-center align-items-center">
        <section class="rounded p-4 bg-white mt-4">
            <h2 class="text-center pb-4">{% trans "Borrar empleado" %}</h2>
            <form method="post">
                {% csrf_token %}
                <p> {% trans "¿Deseas borrar al empleado" %} {{ object.nombre }} {{ object.apellido }}?</p>
                <section class="w-100 d-flex justify-content-center">
                    <button class="mx-2 btn btn-danger">
                        {% trans "Borrar" %}
                    </button>

                    <a href="{% url 'empresa:list-employee' business_id=business_id %}">
                        <button type="button" class="btn btn-light">
                            {% trans "Cancelar" %}
                        </button>
                    </a>
                </section>
            </form>
        </section>
    </section>
</section>
{% endblock content %}
{% block inline_javascript %}
{% endblock %}

lab_ati/templates/pages/employees/detail.html
{% extends "../../base.html" %}
{% load i18n %}

{% block content %}
<section class="general-container w-100">
    {% include "../../common/navigation-bar.html" with back_link=request.META.HTTP_REFERER enlace=list_link %}
    <h2 class="text-center pb-4">{% trans "Información del empleado" %}</h2>
    <section class="card">
        <section class="card-body">
            <p class="card-text"> {% trans 'Nombre' %}: {{ object.nombre }} {{ object.apellido }}</p>
            <p class="card-text">{% trans 'Cedula de identidad o nro de pasaporte' %}: {{ object.ci }} </p>
            <p class="card-text">{% trans 'Empresa a la que pertenece' %}: {{ object.empresa }} </p>
            <p class="card-text">{% trans 'Cargo' %}: {{ object.cargo }} </p>
            <p class="card-text">{% trans 'Teléfono local' %}: {{ object.tlf_local }} </p>
            <p class="card-text">{% trans 'Empresa a la que pertenece' %}: {{ object.tlf_celular }} </p>
            <p class="card-text">{% trans 'País' %}: {{ object.pais }} </p>
            <p class="card-text">{% trans 'Ciudad' %}: {{ object.ciudad }} </p>
            <p class="card-text">{% trans 'Modelo de contratación' %}: {{ object.modalidad_contratacion }} </p>

            <section class="d-flex justify-content-center">
                <a href="{% url 'empresa:edit-employee' business_id=business_id pk=object.id %}">
                    <button class="btn btn-primary">
                        {% trans 'Editar' %}
                    </button>
                </a>
                <a href="{% url 'empresa:delete-employee' business_id=business_id pk=object.id %}"" class="mx-2">
                    <button class="btn btn-danger">
                        {% trans 'Eliminar' %}
                    </button>
                </a>
            </section>
        </section>
      </section>
</section>
{% endblock content %}
{% block inline_javascript %}
<script>
</script>
{% endblock %}

lab_ati/templates/pages/employees/list.html
{% extends "../../base.html" %}
{% load i18n %}
{% block content %}
<section class="general-container">
    <h2 class="text-center pb-4">{% trans "Lista de empleados" %}</h2>
    <!-- {% for message in messages %}
            <div class="toast align-items-center show" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                <div class="toast-body">
                        {{ message }}
                </div>
                <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
    {% endfor %} -->
     
    <form method="POST" class="container d-grid gap-3 pb-4">
        {% csrf_token %}

        <section class="row">
            <section class="d-flex justify-content-between mb-2">
                <h2>{% trans "Gestiona empleados"%}</h2>
                <a href="{% url 'empresa:create-employee' business_id=business_id %}">
                    <button type="button" class="btn btn-primary">
                        <i class="bi bi-plus-lg"></i>
                    </button>
                </a>
            </section>
            
            <table class="table table-success table-striped">
                <thead>
                    <tr>
                        <th>
                            {% trans "ID" %}
                        </th>
                        <th>
                            {% trans "Nombre" %}
                        </th>
                        <th>
                            {% trans "Cedula de identidad o pasaporte" %}
                        </th>
                        <th>
                            {% trans "Acciones" %}
                        </th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for employee in object_list %}
                    <tr>
                        <td>
                            {{ employee.id }}
                        </td>
                        <td>
                            {{ employee.nombre }}            
                        </td>
                        <td>
                            {{ employee.ci }}            
                        </td>
                        <td class="d-flex">
                            <a href="{% url 'empresa:detail-employee' business_id=business_id pk=employee.id %}">
                                <button type="button" class="mx-2 btn btn-info">
                                    <i class="bi bi-search"></i>
                                </button>
                            </a>
                            <a href="{% url 'empresa:edit-employee' business_id=business_id pk=employee.id %}">
                                <button type="button" class="mx-2 btn btn-primary">
                                    <i class="bi bi-pencil-square"></i>
                                </button>
                            </a>
                            <a href="{% url 'empresa:delete-employee' business_id=business_id pk=employee.id %}">
                                <button type="button" class="mx-2 btn btn-danger">
                                    <i class="bi bi-person-x"></i>
                                </button>
                            </a>
                        </td>
                    </tr>   
                    {% endfor %}
                </tbody>
            </table>
            <section class="d-flex justify-content-center w-100">
                {% include "../../common/pagination.html" with is_paginated=is_paginated paginator=paginator page_obj=page_obj %}
            </section>
        </section>
    </form>
</section>
{% endblock content %}
{% block inline_javascript %}
<!-- <script>
    // Obtenemos todos los elementos .toast
    let toasts = document.querySelectorAll('.toast');
    
    // Recorremos los elementos y establecemos un temporizador para cerrarlos
    toasts.forEach((toast) => {
        setTimeout(() => {
            // Ocultamos el toast después de 5 segundos
            toast.hide();
        }, 5000); // Establecemos un tiempo de espera de 5 segundos
    });
    </script> -->
{% endblock %}